# Object file lists.

ccflags-$(CONFIG_ARCH_MULTIPLATFORM) := -I$(srctree)/$(src)/include \
	-I$(srctree)/arch/arm/mach-aspeed/include

obj-$(CONFIG_ARCH_ASPEED)	+= aspeed.o
obj-$(CONFIG_MACH_ASPEED_G5)	+= reset.o
