# Aspeed pinctrl support

ccflags-$(CONFIG_ARCH_MULTIPLATFORM) := \
	-I$(srctree)/arch/arm/mach-aspeed/include

obj-$(CONFIG_PINCTRL_ASPEED)	+= pinctrl-aspeed.o
obj-$(CONFIG_PINCTRL_ASPEED_G4)	+= pinctrl-aspeed-g4.o
obj-$(CONFIG_PINCTRL_ASPEED_G5)	+= pinctrl-aspeed-g5.o
