
ccflags-$(CONFIG_ARCH_MULTIPLATFORM) := \
        -I$(srctree)/arch/arm/mach-aspeed/include

obj-$(CONFIG_SENSORS_ASPEED_PWM_FAN)	+= aspeed-pwm-fan.o
obj-$(CONFIG_SENSORS_ASPEED_ADC)	+= aspeed-adc.o
